package bpf

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -Wall -Werror" Ktrace ../../bpf/ktrace.bpf.c -- -I../../bpf

// NOTE:
// - This package is generated by `go generate` (see Makefile target `generate`).
// - It embeds the compiled BPF object and provides typed maps/program handles.
// - If you see missing symbols like LoadKtraceObjects, run: `make generate`.
